### ISSUE TITLE
Switch to failure crate

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-client-rs#1]
See https://boats.gitlab.io/failure/

**Comment by ovalseven8** [comment]
Just out of curiosity: Why using an experimental/unstable crate for error handling instead of the default/robust way?

**Comment by dbrgn** [comment]
There is no default way so far :) Failure will probably become the default way though: https://boats.gitlab.io/blog/post/2017-11-16-announcing-failure/ Also, the single-error-type model of `error-chain` didn't really work out for us and handling the `ErrorKind` was a bit cumbersome.

Or in other words: `496 additions and 549 deletions`.

**Comment by ovalseven8** [comment]
Thanks for the explanation!
