### ISSUE TITLE
Is the Rust implementation using webrtc and/or capable of NAT traversal?

### ISSUE THREAD

**Issue by rmst** [saltyrtc/saltyrtc-client-rs#72]
Hey, are you guys using WebRTC (e.g. https://github.com/webrtc-rs/webrtc)? I didn't see it in the dependencies. And if not does the Rust implementation have similar NAT traversal capabilities to WebRTC (e.g. via UPnP)

**Comment by dbrgn** [comment]
Right now there is no WebRTC task implementation for Rust, only [the relayed data task](https://github.com/saltyrtc/saltyrtc-task-relayed-data-rs) which uses the signaling server for relaying. So if you use this task, it's not P2P at all. (However, NATs shouldn't be an issue.)

Does that answer your question?

**Comment by rmst** [comment]
Ah, I see! Yes it does, thank you! I just realized that the WebRTC spec doesn't even mandate "advanced" NAT traversal techniques like UPnP, Nat-PMP, etc. No idea if Chromium implements those but it doesn't look like webrtc-rs is implementing these (they obviously do have STUN though). Any plans on doing P2P in Rust for SaltyRTC?

**Comment by dbrgn** [comment]
For NAT traversal, WebRTC simply uses STUN AFAIK. If that fails, TURN is used for relaying.

> Any plans on doing P2P in Rust for SaltyRTC?

Not really, no. We mainly wrote the implementation for [Threema iOS app](https://github.com/threema-ch/threema-ios) but you can forget about background P2P connectivity on iOS, so WebRTC was out of scope. Additionally, when we started, there wasn't any ready-to-use way to call WebRTC from Rust. Nowadays, there's https://webrtc.rs/, but i have no idea how mature it is.

**Comment by lgrahl** [comment]
> No idea if Chromium implements those

They don't. UDP has hole punching capabilities and WebRTC builds on UDP. If you're behind a NAT that does not allow for UDP hole punching (e.g. a symmetric NAT), then you're most likely not in a consumer network and UPnP port forwarding is disabled for security reasons. I generally would not recommend enabling UPnP port forwarding in 2021.

> Any plans on doing P2P in Rust for SaltyRTC?

I think there's a conceptional misunderstanding here. SaltyRTC does not do NAT traversal. It's purpose is establishing a secure data transport channel from A to B via a server C. This channel can then be used to exchange arbitrary data. It is designed to securely exchange information (i.e. signalling data) so a WebRTC P2P connection (which does/tries NAT traversal) can be established. So, while SaltyRTC can help in establishing a P2P connection, it's job is not to do NAT traversal.

**Comment by rmst** [comment]
Thanks for the explanation!
